{% set name = "opentelemetry-instrumentation-pymemcache" %}
{% set version = "0.31b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-pymemcache-{{ version }}.tar.gz
  sha256: 1c3d0773d497900b963138c5e01da22edee0ccdfe6df08aae12ad0d3b5fc108e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.31b0
    - opentelemetry-semantic-conventions ==0.31b0
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - pymemcache ~=1.3
    # - opentelemetry-test ==0.24b0
    # - pymemcache ~=1.3
    # - opentelemetry-test ==0.25b0
    # - pymemcache ~=1.3
    # - opentelemetry-test ==0.25b1
    # - pymemcache ~=1.3
    # - opentelemetry-test-utils ==0.26b1
    # - pymemcache ~=1.3
    # - opentelemetry-test-utils ==0.27b0
    # - pymemcache ~=1.3
    # - opentelemetry-test-utils ==0.28b0
    # - pymemcache ~=1.3
    # - opentelemetry-test-utils ==0.28b1
    # - pymemcache ~=1.3
    # - opentelemetry-test-utils ==0.29b0
    # - pymemcache <4,>=1.3.5
    # - opentelemetry-test-utils ==0.30b0
    # - pymemcache <4,>=1.3.5
    # - opentelemetry-test-utils ==0.30b1
    # - pymemcache <4,>=1.3.5
    # - opentelemetry-test-utils ==0.31b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pymemcache
  summary: OpenTelemetry pymemcache instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
